/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_JniUtils */

#ifndef _Included_com_example_hellojni_JniUtils
#define _Included_com_example_hellojni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_JniUtils
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_JniUtils_getName
  (JNIEnv *, jobject,jstring);

#ifdef __cplusplus
}
#endif
#endif
